#!/usr/bin/env python

import shutil
from datetime import datetime
from pathlib import Path
from typing import cast

from pystac import CatalogType

from stactools.met_office_deterministic.stac import (
    MetOfficeCollection,
    create_collection,
    create_item,
)

root = Path(__file__).parents[1]
examples = root / "examples"

if examples.exists():
    shutil.rmtree(examples)
    examples.mkdir()

for collection_id in [
    "met-office-global-deterministic-10km-surface",
    "met-office-global-deterministic-10km-height",
    "met-office-global-deterministic-10km-pressure",
    "met-office-uk-deterministic-2km-surface",
    "met-office-uk-deterministic-2km-height",
    "met-office-uk-deterministic-2km-pressure",
]:
    collection_dir = examples / collection_id
    collection_dir.mkdir()
    collection = create_collection(cast(MetOfficeCollection, collection_id))
    items = [
        create_item(
            collection=cast(MetOfficeCollection, collection_id),
            reference_time=datetime(2025, 10, 1, 0),
            valid_time=datetime(2025, 10, 1, hour),
        )
        for hour in [0, 1, 2]
    ]
    collection.add_items(items)
    collection.normalize_hrefs(str(collection_dir))
    collection.save(CatalogType.SELF_CONTAINED)
