# Global Deterministic Variables by Collection Type

global_pressure_variables = [
    "height_ASL_on_pressure_levels",
    "relative_humidity_on_pressure_levels",
    "temperature_on_pressure_levels",
    "wet_bulb_potential_temperature_on_pressure_levels",
    "wind_direction_on_pressure_levels",
    "wind_speed_on_pressure_levels",
    "wind_vertical_velocity_on_pressure_levels",
]

global_height_variables = [
    "cloud_amount_on_height_levels",
]

global_surface_variables = [
    "CAPE_mixed_layer_lowest_500m",
    "CAPE_most_unstable_below_500hPa",
    "CAPE_surface",
    "CIN_mixed_layer_lowest_500m",
    "CIN_most_unstable_below_500hPa",
    "CIN_surface",
    "cloud_amount_below_1000ft_ASL",
    "cloud_amount_of_high_cloud",
    "cloud_amount_of_low_cloud",
    "cloud_amount_of_medium_cloud",
    "cloud_amount_of_total_cloud",
    "cloud_amount_of_total_convective_cloud",
    "fog_fraction_at_screen_level",
    "latent_heat_flux_at_surface_mean",
    "precipitation_accumulation",
    "precipitation_rate",
    "pressure_at_mean_sea_level",
    "pressure_at_tropopause",
    "radiation_flux_in_longwave_downward_at_surface",
    "radiation_flux_in_shortwave_direct_downward_at_surface",
    "radiation_flux_in_shortwave_total_downward_at_surface",
    "radiation_flux_in_uv_downward_at_surface",
    "rainfall_accumulation",
    "rainfall_rate",
    "rainfall_rate_from_convection",
    "rainfall_rate_from_convection_max",
    "relative_humidity_at_screen_level",
    "snow_depth_water_equivalent",
    "snowfall_rate",
    "snowfall_rate_from_convection",
    "snowfall_rate_from_convection_max",
    "snowfall_rate_from_convection_mean",
    "temperature_at_screen_level",
    "temperature_at_screen_level_max",
    "temperature_at_screen_level_min",
    "temperature_at_surface",
    "temperature_at_tropopause",
    "temperature_of_dew_point_at_screen_level",
    "visibility_at_screen_level",
    "wind_direction_at_10m",
    "wind_gust_at_10m",
    "wind_gust_at_10m_max",
    "wind_speed_at_10m",
]

# UK Deterministic Variables by Collection Type

uk_pressure_variables = [
    "height_ASL_on_pressure_levels",
    "relative_humidity_on_pressure_levels",
    "temperature_on_pressure_levels",
    "wet_bulb_potential_temperature_on_pressure_levels",
    "wind_direction_on_pressure_levels",
    "wind_speed_on_pressure_levels",
]

uk_height_variables = [
    "cloud_amount_on_height_levels",
    "temperature_on_height_levels",
    "wind_direction_on_height_levels",
    "wind_speed_on_height_levels",
]

uk_surface_variables = [
    "CAPE_most_unstable_below_500hPa",
    "CAPE_surface",
    "cloud_amount_below_1000ft_ASL",
    "cloud_amount_of_high_cloud",
    "cloud_amount_of_low_cloud",
    "cloud_amount_of_medium_cloud",
    "cloud_amount_of_total_cloud",
    "fog_fraction_at_screen_level",
    "hail_fall_accumulation",
    "hail_fall_rate",
    "height_AGL_at_cloud_base_where_cloud_cover_2p5_oktas",
    "height_AGL_at_freezing_level",
    "height_AGL_at_wet_bulb_freezing_level",
    "landsea_mask",
    "lightning_flash_accumulation",
    "precipitation_accumulation",
    "precipitation_rate",
    "pressure_at_mean_sea_level",
    "pressure_at_surface",
    "radiation_flux_in_longwave_downward_at_surface",
    "radiation_flux_in_shortwave_diffuse_downward_at_surface",
    "radiation_flux_in_shortwave_direct_downward_at_surface",
    "radiation_flux_in_shortwave_total_downward_at_surface",
    "radiation_flux_in_uv_downward_at_surface",
    "rainfall_accumulation",
    "rainfall_rate",
    "relative_humidity_at_screen_level",
    "sensible_heat_flux_at_surface",
    "snow_depth_water_equivalent",
    "snowfall_accumulation",
    "snowfall_rate",
    "temperature_at_screen_level",
    "temperature_at_screen_level_max",
    "temperature_at_screen_level_min",
    "temperature_at_surface",
    "temperature_of_dew_point_at_screen_level",
    "visibility_at_screen_level",
    "wind_direction_at_10m",
    "wind_gust_at_10m",
    "wind_gust_at_10m_max",
    "wind_speed_at_10m",
]
